<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ $data->subject }}</title>
</head>

<body>
  <p>This e-mail was generated by PMU - Project Monitoring & Management System</p>
  <span>********************************</span>
  <br>
  <span>Drafted at {{ $data->updated_at }} by {{ $data->updated_by }}</span>
  <br>
  <span>{{ $data->additional }}</span>
  <br>
  <span>********************************</span>
  <br>
  <div>
    {!! $data->remark !!}
  </div>
  <p>********************************</p>
  <span>Issue Purpose: <b>For {{ $data->issue_purpose }}</b></span>
  <br>
  <span>Document No: <b>{{ $data->document_no }}</b></span>
  <br>
  <span>Document Title: <b>{{ $data->title }}</b></span>
  <br>
  <span>Document Type: <b>{{ $data->type }}</b></span>
  <br>
  <span>Rev. No: <b>{{ $data->rev_no }}</b></span>
  <br>
  <span>Issued by: <b>{{ $data->issued_by }}</b></span>
  <br>
  <span>Issue Status: <b>{{ $data->status }}</b></span>
  <br>
  <span>Click <a href="{{ $data->link }}">here </a>to go to the document</span>
  <br>
  <br>
  <br>
  <small>--</small>
  <br>
  <small style="color: rgb(136,136,136)">Regards,</small>
  <br>
  <small style="color: rgb(136,136,136)">Project Management & Monitoring System</small>
  <br>
  <small style="color: rgb(136,136,136)">Project Management Unit</small>
  <br>
  <small style="color: rgb(136,136,136)">PT. Geo Dipa Energi (Persero)</small>
</body>

</html>